name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  frontend-ci:
    name: Frontend CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install frontend dependencies
        run: |
          cd finance-frontend
          npm install

      - name: Run frontend tests
        run: |
          cd finance-frontend
          npm test --if-present

      - name: Build frontend
        run: |
          cd finance-frontend
          npm run build

  backend-ci:
    name: Backend CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install backend dependencies
        run: |
          cd finance-backend
          npm install

      - name: Run backend tests
        run: |
          cd finance-backend
          npm test --if-present
